export interface CategoryConfig {
  name: string
  headline: string
  sub: string
  badge: string
  image: string
  gradient: string
  accentClass: string       // Tailwind text color for the badge
  ctaLabel: string
  ctaHref: string
  bottomBannerHeadline: string
  bottomBannerSub: string
  bottomBannerCta: string
  bottomBannerHref: string
}

const CONFIGS: Record<string, CategoryConfig> = {
  rones: {
    name: 'Rones',
    headline: 'Rones del\nCaribe y el Mundo',
    sub: '134 etiquetas · Brugal, Barceló, Puntacana y más',
    badge: 'Rones · Nacional e importado',
    image: 'https://images.unsplash.com/photo-1569529465841-dfecdab7503b?auto=format&fit=crop&w=1600&h=400&q=80',
    gradient: 'from-amber-950/90 via-amber-900/60 to-transparent',
    accentClass: 'text-amber-400',
    ctaLabel: 'Los más vendidos',
    ctaHref: '/catalog?category=rones&sort=price_asc',
    bottomBannerHeadline: 'Ron Dominicano,\nOrgullo del Caribe',
    bottomBannerSub: 'Brugal 1888, Barceló Imperial, Puntacana Muy Viejo — la mejor selección.',
    bottomBannerCta: 'Ver todos los rones',
    bottomBannerHref: '/catalog?category=rones',
  },
  vinos: {
    name: 'Vinos',
    headline: 'Vinos del\nMundo',
    sub: '383 etiquetas · Tintos, blancos, rosados y espumantes',
    badge: 'Vinos · Importados y seleccionados',
    image: 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?auto=format&fit=crop&w=1600&h=400&q=80',
    gradient: 'from-[#3d0f1f]/95 via-[#3d0f1f]/65 to-transparent',
    accentClass: 'text-rose-400',
    ctaLabel: 'Ver colección',
    ctaHref: '/catalog?category=vinos&sort=price_asc',
    bottomBannerHeadline: 'Para Cada\nOcasión un Vino',
    bottomBannerSub: 'Desde RD$688 hasta reservas exclusivas. Casillero, Santa Rita, Termanthia.',
    bottomBannerCta: 'Explorar vinos',
    bottomBannerHref: '/catalog?category=vinos',
  },
  whisky: {
    name: 'Whisky',
    headline: 'Whisky · Scotch\ny Bourbon',
    sub: '164 etiquetas · Dewars, Johnnie Walker, single malts',
    badge: 'Whisky · Scotch · Bourbon · Japonés',
    image: 'https://images.unsplash.com/photo-1584283604310-2aab12743a01?auto=format&fit=crop&w=1600&h=400&q=80',
    gradient: 'from-stone-950/92 via-stone-900/65 to-transparent',
    accentClass: 'text-amber-300',
    ctaLabel: 'Single malts',
    ctaHref: '/catalog?category=whisky&min_price=3000',
    bottomBannerHeadline: 'Del Scotch al\nBourbon Americano',
    bottomBannerSub: 'Dewars 18 Years, Johnnie Walker, blends y single malts. Envío en 30 min.',
    bottomBannerCta: 'Ver whiskies',
    bottomBannerHref: '/catalog?category=whisky',
  },
  cervezas: {
    name: 'Cervezas',
    headline: 'Cervezas\ndel Mundo',
    sub: '203 etiquetas · Nacionales, importadas y artesanales',
    badge: 'Cervezas · Nacional e internacional',
    image: 'https://images.unsplash.com/photo-1608270586620-248524c67de9?auto=format&fit=crop&w=1600&h=400&q=80',
    gradient: 'from-yellow-950/90 via-yellow-900/55 to-transparent',
    accentClass: 'text-yellow-400',
    ctaLabel: 'Mejores precios',
    ctaHref: '/catalog?category=cervezas&sort=price_asc',
    bottomBannerHeadline: 'Fría y Lista\npara Servir',
    bottomBannerSub: 'Desde Presidente y Sol hasta lagers europeas importadas. Desde RD$55.',
    bottomBannerCta: 'Ver cervezas',
    bottomBannerHref: '/catalog?category=cervezas',
  },
  espumantes: {
    name: 'Espumantes',
    headline: 'Champagne,\nCava y Prosecco',
    sub: '44 etiquetas · Para celebrar cada momento',
    badge: 'Espumantes · Burbujas para todo',
    image: 'https://images.unsplash.com/photo-1548941015-bab2c451a7fa?auto=format&fit=crop&w=1600&h=400&q=80',
    gradient: 'from-slate-950/90 via-slate-900/60 to-transparent',
    accentClass: 'text-yellow-300',
    ctaLabel: 'Ver colección',
    ctaHref: '/catalog?category=espumantes&sort=price_asc',
    bottomBannerHeadline: 'Brinda con\nEstilo',
    bottomBannerSub: 'Champagne, prosecco y cavas para cada celebración. Entrega en 30 min.',
    bottomBannerCta: 'Ver espumantes',
    bottomBannerHref: '/catalog?category=espumantes',
  },
  licores: {
    name: 'Licores',
    headline: 'Licores y\nEspecialidades',
    sub: '79 etiquetas · Cremas, anís, triple sec y más',
    badge: 'Licores · La coctelería completa',
    image: 'https://images.unsplash.com/photo-1574944985070-8f3ebc6b79d2?auto=format&fit=crop&w=1600&h=400&q=80',
    gradient: 'from-purple-950/90 via-purple-900/60 to-transparent',
    accentClass: 'text-purple-400',
    ctaLabel: 'Ver colección',
    ctaHref: '/catalog?category=licores&sort=price_asc',
    bottomBannerHeadline: 'Todo para tu\nCoctelería',
    bottomBannerSub: 'Triple sec, cremas, amaretto y más. Los ingredientes que no pueden faltar.',
    bottomBannerCta: 'Explorar licores',
    bottomBannerHref: '/catalog?category=licores',
  },
  'bebidas-sin-alcohol': {
    name: 'Sin Alcohol',
    headline: 'Bebidas\nSin Alcohol',
    sub: '84 etiquetas · Refrescos, tónicas y alternativas premium',
    badge: 'Sin Alcohol · Para todos',
    image: 'https://images.unsplash.com/photo-1547592166-23ac45744acd?auto=format&fit=crop&w=1600&h=400&q=80',
    gradient: 'from-teal-950/90 via-teal-900/55 to-transparent',
    accentClass: 'text-teal-400',
    ctaLabel: 'Ver opciones',
    ctaHref: '/catalog?category=bebidas-sin-alcohol&sort=price_asc',
    bottomBannerHeadline: 'Sabor sin\nCompromisos',
    bottomBannerSub: 'Hard seltzers, tónicas, aguas premium y bebidas sin alcohol de primera.',
    bottomBannerCta: 'Ver sin alcohol',
    bottomBannerHref: '/catalog?category=bebidas-sin-alcohol',
  },
  'cocteles-listos': {
    name: 'Cocteles',
    headline: 'Cocteles\nListos para Tomar',
    sub: '36 etiquetas · Ready-to-drink y mezclas premium',
    badge: 'Cocteles · Ready-to-drink',
    image: 'https://images.unsplash.com/photo-1536935338788-846bb9981813?auto=format&fit=crop&w=1600&h=400&q=80',
    gradient: 'from-pink-950/90 via-pink-900/55 to-transparent',
    accentClass: 'text-pink-400',
    ctaLabel: 'Ver cocteles',
    ctaHref: '/catalog?category=cocteles-listos&sort=price_asc',
    bottomBannerHeadline: 'Abre, Sirve\ny Disfruta',
    bottomBannerSub: 'BuzzBallz, High Noon y más. Perfectos para la playa o la piscina.',
    bottomBannerCta: 'Ver todos',
    bottomBannerHref: '/catalog?category=cocteles-listos',
  },
  mamajuana: {
    name: 'Mamajuana',
    headline: 'Mamajuana\nDominicana',
    sub: '13 etiquetas · El sabor tradicional del Caribe',
    badge: 'Mamajuana · Tradición dominicana',
    image: 'https://images.unsplash.com/photo-1569529465841-dfecdab7503b?auto=format&fit=crop&w=1600&h=400&q=80',
    gradient: 'from-red-950/90 via-red-900/60 to-transparent',
    accentClass: 'text-red-400',
    ctaLabel: 'Ver colección',
    ctaHref: '/catalog?category=mamajuana&sort=price_asc',
    bottomBannerHeadline: 'Sabor\nTradicional RD',
    bottomBannerSub: 'La mamajuana — el elixir dominicano. Hecha con ron, vino y miel.',
    bottomBannerCta: 'Ver mamajuanas',
    bottomBannerHref: '/catalog?category=mamajuana',
  },
  'tequila-y-mezcal': {
    name: 'Tequila & Mezcal',
    headline: 'Tequila\ny Mezcal',
    sub: 'Agave 100% · De Jalisco a tu mesa',
    badge: 'Tequila & Mezcal · México auténtico',
    image: 'https://images.unsplash.com/photo-1547619292-240b3f3b6fe2?auto=format&fit=crop&w=1600&h=400&q=80',
    gradient: 'from-orange-950/90 via-orange-900/60 to-transparent',
    accentClass: 'text-orange-400',
    ctaLabel: 'Ver tequilas',
    ctaHref: '/catalog?category=tequila-y-mezcal&sort=price_asc',
    bottomBannerHeadline: '100% Agave,\n100% México',
    bottomBannerSub: 'El Jimador, tequilas blanco, reposado y añejo. Auténtico y premium.',
    bottomBannerCta: 'Explorar',
    bottomBannerHref: '/catalog?category=tequila-y-mezcal',
  },
  'vermut-y-aperitivos': {
    name: 'Vermut',
    headline: 'Vermut y\nAperitivos',
    sub: '11 etiquetas · Para abrir el paladar',
    badge: 'Vermut · Aperitivos · Amari',
    image: 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?auto=format&fit=crop&w=1600&h=400&q=80',
    gradient: 'from-rose-950/90 via-rose-900/60 to-transparent',
    accentClass: 'text-rose-400',
    ctaLabel: 'Ver aperitivos',
    ctaHref: '/catalog?category=vermut-y-aperitivos&sort=price_asc',
    bottomBannerHeadline: 'El Arte del\nAperitivo',
    bottomBannerSub: 'Vermut, amari y aperitivos para despertar el paladar antes de la comida.',
    bottomBannerCta: 'Ver vermuts',
    bottomBannerHref: '/catalog?category=vermut-y-aperitivos',
  },
}

const DEFAULT_CONFIG: CategoryConfig = {
  name: 'Catálogo',
  headline: 'Todo lo que\nBuscas,',
  sub: 'La mayor selección de licores en Puerto Plata',
  badge: 'Puerto Plata · Selección completa',
  image: 'https://images.unsplash.com/photo-1569529465841-dfecdab7503b?auto=format&fit=crop&w=1600&h=400&q=80',
  gradient: 'from-black/85 via-black/60 to-black/20',
  accentClass: 'text-accent',
  ctaLabel: 'Mejores precios',
  ctaHref: '/catalog?sort=price_asc',
  bottomBannerHeadline: 'Lleva 6, Ahorra 10%',
  bottomBannerSub: 'Cualquier combinación de botellas. Descuento automático.',
  bottomBannerCta: 'Ver ofertas',
  bottomBannerHref: '/catalog?sort=price_asc',
}

export function getCategoryConfig(category?: string): CategoryConfig {
  if (!category) return DEFAULT_CONFIG
  return CONFIGS[category] ?? DEFAULT_CONFIG
}
